version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,sqs,sns,dynamodb,cloudwatch,logs
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
