openapi: 3.0.1
info:
  title: API de Pedidos
  version: 1.0.0
paths:
  /pedidos:
    post:
      summary: Criar novo pedido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: string
                itens:
                  type: array
                  items:
                    type: string
                mesa:
                  type: integer
      responses:
        '200':
          description: Pedido criado com sucesso
